DESHAB_USERCONF_V1
computer=DESHAB-PC
username=admin
passwordSha256=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
locale=zh-CN
region=CN
timezone=Asia/Shanghai
keyboard=us-qwerty
theme=dark
network.mode=disabled
network.ssid=
network.password=
network.ip=dhcp
network.dns=auto
